# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Badlion.BadlionClient
PackageVersion: 3.15.1
PackageLocale: en-US
Publisher: ELS Gaming Online
PackageName: Badlion Client
License: Proprietary
Copyright: Copyright © 2023 Badlion
ShortDescription: Badlion Client
ManifestType: defaultLocale
ManifestVersion: 1.4.0
