# Created using wingetcreate 1.9.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Arc.Arc
PackageVersion: 1.16.0.0
PackageLocale: en-US
Publisher: Arc
PackageName: Arc Browser
License: Proprietary
ShortDescription: Experience a calmer, more personal internet in this browser designed for you. Let go of the clicks, the clutter, the distractions with the Arc browser.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
